export const copy = {
  zh: {
    title: "巧移火柴我最棒",
    subtitle: "只移动一根火柴，让等式成立。",
    newPuzzle: "新题",
    undo: "复原",
    answer: "答案",
    hideAnswer: "隐藏答案",
    share: "分享题目",
    difficulty: "难度",
    easy: "入门",
    easyLabel: "入门",
    hard: "进阶",
    hardLabel: "进阶",
    rotateHint: "进阶模式建议横屏，操作空间更充足。",
    timer: "计时",
    sound: "音效",
    solved: "已答",
    streak: "连续",
    bypassed: "跳过",
    clearStats: "清零统计",
    answersFound: "答案",
    selectHint: "点击一根可移动的火柴，再点击虚线位置。",
    selectedHint: "选择一个虚线位置放下火柴。",
    correct: "正确！点击新题继续。",
    wrong: "还不对，再试一次。",
    timeout: "时间到。可以复原、看答案或换一题。",
    voiceListening: "正在听，请说出完整算式。",
    voiceNoMatch: "没有识别到可行答案，请再试一次。",
    voiceUnsupported: "当前浏览器不支持语音识别。",
    voicePermission: "需要允许麦克风权限才能语音解题。",
    shareCopied: "题目链接已复制。",
    shareFailed: "无法复制题目链接。",
    answerTitle: "可行答案",
    voice: "语音",
    languageLabel: "语言",
    gameSettingsLabel: "游戏设置",
    puzzleLabel: "火柴算式谜题",
    equalsLabel: "等号",
    segmentLabel: "第 {segment} 根火柴",
  },
  en: {
    title: "iMatchstick",
    subtitle: "Move exactly one matchstick to correct the equation.",
    newPuzzle: "New",
    undo: "Undo",
    answer: "Answer",
    hideAnswer: "Hide",
    share: "Share puzzle",
    difficulty: "Difficulty",
    easy: "Intro",
    easyLabel: "Beginner",
    hard: "Adv",
    hardLabel: "Advanced",
    rotateHint: "Landscape is recommended for Advanced mode.",
    timer: "Timer",
    sound: "Sound",
    solved: "Solved",
    streak: "Streak",
    bypassed: "Skipped",
    clearStats: "Reset stats",
    answersFound: "Answers",
    selectHint: "Tap a movable match, then tap a dashed position.",
    selectedHint: "Choose a dashed position for the match.",
    correct: "Correct. Start a new puzzle when ready.",
    wrong: "Not quite. Try another move.",
    timeout: "Time is up. Undo, view answers, or start a new puzzle.",
    voiceListening: "Listening. Say the full equation.",
    voiceNoMatch: "No valid answer recognized. Try again.",
    voiceUnsupported: "Speech recognition is not supported in this browser.",
    voicePermission: "Microphone permission is required for voice answers.",
    shareCopied: "Puzzle link copied.",
    shareFailed: "Unable to copy puzzle link.",
    answerTitle: "Valid answers",
    voice: "Voice",
    languageLabel: "Language",
    gameSettingsLabel: "Game settings",
    puzzleLabel: "Matchstick puzzle",
    equalsLabel: "Equals",
    segmentLabel: "Matchstick segment {segment}",
  },
} as const;

export type Language = keyof typeof copy;
export type CopyText = (typeof copy)[Language];
