export const copy = {
  zh: {
    title: "巧移火柴我最棒",
    subtitle: "只移动一根火柴，让等式成立。",
    newPuzzle: "新题",
    undo: "复原",
    answer: "答案",
    hideAnswer: "隐藏答案",
    share: "分享题目",
    difficulty: "级别",
    decreaseDifficulty: "降低难度分组",
    increaseDifficulty: "提高难度分组",
    difficultyValue: "第 {level} 组：{label}",
    difficultyLabels: {
      level0: "0级",
      easiest: "最简单",
      easy: "简单",
      easyPlus: "简单+",
      medium: "中等",
      mediumPlus: "中等+",
      hard: "难",
      hardPlus: "难+",
      expert: "最难",
    },
    difficultyDescriptions: {
      level0: "一位数加减一位数，自移。",
      easiest: "右侧自移：只需算左侧，再改右侧。",
      easy: "左侧单数字自移：反推一个操作数。",
      easyPlus: "右侧外加火柴：源和目标都要合法。",
      medium: "左侧跨数字移动：左侧两个数一起变。",
      mediumPlus: "改运算符：算式结构变化。",
      hard: "跨等号移动：等式两边同时变化。",
      hardPlus: "多位数高位变化：数值跨度大。",
      expert: "多位数跨等号、改符号或多候选：搜索空间最大。",
    },
    rotateHint: "较高难度建议横屏，操作空间更充足。",
    timer: "计时",
    sound: "音效",
    solved: "已答",
    streak: "连续",
    bypassed: "跳过",
    clearStats: "清零统计",
    answersFound: "答案",
    selectHint: "点击一根可移动的火柴，再点击虚线位置。",
    selectedHint: "选择一个虚线位置放下火柴。",
    correct: "正确！点击新题，或双击背景继续。",
    wrong: "还不对，再试一次。",
    timeout: "时间到。可以查看答案或开始新题。",
    voiceListening: "正在听，请说出完整算式。",
    voiceNoMatch: "没有识别到可行答案，请再试一次。",
    voiceUnsupported: "当前浏览器不支持语音识别。",
    voicePermission: "需要允许麦克风权限才能语音解题。",
    shareCopied: "题目链接已复制。",
    shareFailed: "无法复制题目链接。",
    answerTitle: "可行答案",
    voice: "语音",
    cancelVoice: "取消语音",
    languageLabel: "语言",
    gameSettingsLabel: "游戏设置",
    puzzleLabel: "火柴算式谜题",
    equalsLabel: "等号",
    segmentLabel: "第 {segment} 根火柴",
  },
  en: {
    title: "iMatchstick",
    subtitle: "Move exactly one matchstick to correct the equation.",
    newPuzzle: "New",
    undo: "Undo",
    answer: "Answer",
    hideAnswer: "Hide",
    share: "Share puzzle",
    difficulty: "Level",
    decreaseDifficulty: "Decrease difficulty group",
    increaseDifficulty: "Increase difficulty group",
    difficultyValue: "Group {level}: {label}",
    difficultyLabels: {
      level0: "Level 0",
      easiest: "Easiest",
      easy: "Easy",
      easyPlus: "Easy+",
      medium: "Medium",
      mediumPlus: "Medium+",
      hard: "Hard",
      hardPlus: "Hard+",
      expert: "Expert",
    },
    difficultyDescriptions: {
      level0: "One-digit equation with a self move.",
      easiest:
        "Right-side self move: calculate the left side, then fix the result.",
      easy: "Left-side single-digit self move: infer one operand.",
      easyPlus:
        "Right-side external drop: both source and target must stay valid.",
      medium:
        "Left-side cross-digit move: two left-side numbers change together.",
      mediumPlus: "Operator change: the equation structure changes.",
      hard: "Cross-equals move: both sides change at once.",
      hardPlus: "Multi-digit high-place change: the numeric jump is large.",
      expert:
        "Multi-digit cross-equals, operator change, or multiple candidates: largest search space.",
    },
    rotateHint: "Landscape is recommended for higher difficulties.",
    timer: "Timer",
    sound: "Sound",
    solved: "Solved",
    streak: "Streak",
    bypassed: "Skipped",
    clearStats: "Reset stats",
    answersFound: "Answers",
    selectHint: "Tap a movable match, then tap a dashed position.",
    selectedHint: "Choose a dashed position for the match.",
    correct: "Correct. Tap New or double-click the background to continue.",
    wrong: "Not quite. Try another move.",
    timeout: "Time is up. View answers or start a new puzzle.",
    voiceListening: "Listening. Say the full equation.",
    voiceNoMatch: "No valid answer recognized. Try again.",
    voiceUnsupported: "Speech recognition is not supported in this browser.",
    voicePermission: "Microphone permission is required for voice answers.",
    shareCopied: "Puzzle link copied.",
    shareFailed: "Unable to copy puzzle link.",
    answerTitle: "Valid answers",
    voice: "Voice",
    cancelVoice: "Cancel voice",
    languageLabel: "Language",
    gameSettingsLabel: "Game settings",
    puzzleLabel: "Matchstick puzzle",
    equalsLabel: "Equals",
    segmentLabel: "Matchstick segment {segment}",
  },
} as const;

export type Language = keyof typeof copy;
export type CopyText = (typeof copy)[Language];
